### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{app/com.onfido.android.sdk.capture.ui.OnfidoActivity}: kotlin.TypeCastException: null cannot be cast to non-null type com.onfido.android.sdk.capture.OnfidoConfig

### ISSUE THREAD

**Issue by pouriabagheri** [onfido/react-native-sdk#18]
we have received the following crash report from our production app
OS Version : Marshmallow (v6)(Level 23)
Device: Nexus 4 
SDK Version : onfido/react-native-sdk": "^1.2.3"

Note: on this specific case we received similar error log on other SDKs that we use on our app with similar exception message. we suspect this could be a side effect or a react native bug.

**stacktrace:**

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{app/com.onfido.android.sdk.capture.ui.OnfidoActivity}: kotlin.TypeCastException: null cannot be cast to non-null type com.onfido.android.sdk.capture.OnfidoConfig
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
	 at android.app.ActivityThread.-wrap11(ActivityThread.java)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:148)
	 at android.app.ActivityThread.main(ActivityThread.java:5421)
	 at java.lang.reflect.Method.invoke(Method.java)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Caused by: 
kotlin.TypeCastException: null cannot be cast to non-null type com.onfido.android.sdk.capture.OnfidoConfig
	 at com.onfido.android.sdk.capture.ui.OnfidoActivity.getOnfidoConfig(OnfidoActivity.java)
	 at com.onfido.android.sdk.capture.ui.BaseActivity.onCreate(BaseActivity.java)
	 at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(OnfidoActivity.java)
	 at android.app.Activity.performCreate(Activity.java:6280)
	 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
	 at android.app.ActivityThread.-wrap11(ActivityThread.java)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:148)
	 at android.app.ActivityThread.main(ActivityThread.java:5421)
	 at java.lang.reflect.Method.invoke(Method.java)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


```

**Comment by eraxyz** [comment]
Hello @pouriabagheri, is this still an issue? If so, could you try using the latest version of our react native SDK?

**Comment by tasacsachin** [comment]
i integrate latest sdk
"@onfido/react-native-sdk": "^3.0.0",

and tries to run Onfido.start function as shows in the documentation, app crashes throwing same error

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rootspaceai/com.onfido.android.sdk.capture.ui.OnfidoActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
