### ISSUE TITLE
Crash on android while trying to scan an ID

### ISSUE THREAD

**Issue by rpopovici** [onfido/react-native-sdk#30]
I am using ejected expo 41 with RN 0.63.4

The app crashes on android while trying to scan an ID

This is what I have in ScanID class

```
  const startSDK = () => {
    Onfido.start({
      sdkToken: ONFIDO_MOBILE_TOKEN,
      flowSteps: {
        welcome: true,
        captureFace: {
          type: OnfidoCaptureType.VIDEO,
        },
        captureDocument: {
          docType: OnfidoDocumentType.PASSPORT,
          countryCode: OnfidoCountryCode.USA,
        },
      },
    })
      .then((res) => console.warn('OnfidoSDK: Success:', JSON.stringify(res)))
      .catch((err) => console.warn('OnfidoSDK: Error:', err.code, err.message))
  }
```

Reason: 
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.app/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

Stacktrace:
```
FATAL EXCEPTION: main
Process: com.test.app, PID: 28671
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.app/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2844)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2923)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6617)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
at com.google.gson.Gson.fromJson(Gson.java:927)
at com.google.gson.Gson.fromJson(Gson.java:892)
at com.google.gson.Gson.fromJson(Gson.java:841)
at com.google.gson.Gson.fromJson(Gson.java:813)
at com.onfido.api.client.token.sdk.model.SDKTokenPayload.parseSDKTokenPayload(SDKTokenPayload.java:31)
at com.onfido.api.client.token.sdk.url.IDVUrlCreator.createApiUrl(IDVUrlCreator.java:15)
at com.onfido.api.client.token.sdk.SDKToken.buildUrl(SDKToken.java:36)
at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:34)
at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient(Unknown Source:18)
at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPI(Unknown Source:9)
at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:10)
at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:0)
at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:4)
at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:0)
at com.onfido.dagger.internal.a.get(Unknown Source:13)
at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:34)
at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:2)
at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject(Unknown Source:2)
at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(Unknown Source:20)
at android.app.Activity.performCreate(Activity.java:6984)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2797)
... 9 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
... 31 more
```

**Comment by rpopovici** [comment]
Might be related to https://github.com/onfido/onfido-android-sdk/issues/84
