### ISSUE TITLE
Android app crash on calling Onfido.start 

### ISSUE THREAD

**Issue by tasacsachin** [onfido/react-native-sdk#59]
I tried to call Onfido.start function

Onfido.start({
            sdkToken: ' ', //api_sandbox key from server
            flowSteps: {
                welcome: true,
                captureFace: {
                    type: OnfidoCaptureType.VIDEO,
                },
                captureDocument: {
                    docType: OnfidoDocumentType.DRIVING_LICENCE,
                    countryCode: OnfidoCountryCode.GBR,
                },
            },
        })
            .then(res => {
                console.warn('OnfidoSDK: Success:', JSON.stringify(res))
            })
            .catch(err => {
                console.warn('OnfidoSDK: Error:', err.code, err.message)
            });

the app crashes with error shown below

Process: com.rootspaceai, PID: 12574
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rootspaceai/com.onfido.android.sdk.capture.ui.OnfidoActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.onfido.api.client.token.sdk.model.SDKTokenPayload.parseSDKTokenPayload(SDKTokenPayload.java:49)
        at com.onfido.api.client.token.sdk.url.IDVUrlCreator.createApiUrl(IDVUrlCreator.java:15)
        at com.onfido.api.client.token.sdk.SDKToken.buildUrl(SDKToken.java:37)
        at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:34)
        at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient(Unknown Source:18)
        at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPIV3(Unknown Source:7)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIV3Factory.provideOnfidoAPIV3(Unknown Source:0)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIV3Factory.get(Unknown Source:10)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIV3Factory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:4)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(Unknown Source:2)
        at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(Unknown Source:0)
        at a.a.get(Unknown Source:13)
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.onfidoPresenter(Unknown Source:19)
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.injectOnfidoActivity(Unknown Source:7)
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject(Unknown Source:0)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.setupPresenterWith(Unknown Source:12)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(Unknown Source:54)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        at com.google.gson.Gson.fromJson(Gson.java:927) 
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at com.onfido.api.client.token.sdk.model.SDKTokenPayload.parseSDKTokenPayload(SDKTokenPayload.java:49) 
        at com.onfido.api.client.token.sdk.url.IDVUrlCreator.createApiUrl(IDVUrlCreator.java:15) 
        at com.onfido.api.client.token.sdk.SDKToken.buildUrl(SDKToken.java:37) 
        at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:34) 
        at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient(Unknown Source:18) 
        at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPIV3(Unknown Source:7) 
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIV3Factory.provideOnfidoAPIV3(Unknown Source:0) 
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIV3Factory.get(Unknown Source:10) 
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIV3Factory.get(Unknown Source:0) 
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:4) 
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:0) 
        at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(Unknown Source:2) 
        at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(Unknown Source:0) 
        at a.a.get(Unknown Source:13) 
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.onfidoPresenter(Unknown Source:19) 
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.injectOnfidoActivity(Unknown Source:7) 
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject(Unknown Source:0) 
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.setupPresenterWith(Unknown Source:12) 
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(Unknown Source:54) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by ferchorecalt** [comment]
Hi, I have the same issue. Please your help!

**Comment by tasacsachin** [comment]
Hi @ferchorecalt ...you found something to resolve this issue...?

**Comment by ferchorecalt** [comment]
Hi @tasacsachin , we fixed it, removing "minify" property of the release configuration. And we created a ticket to Onfido with the issue.

**Comment by tasacsachin** [comment]
Hi @ferchorecalt , Can you please let me know in detail to how to fix this issue....i need this to be fixed, Please explain me the steps to fix this.
Thanks in advance

**Comment by WladimirBarra** [comment]
Hello! (in our case) We fixed this by making some changes in the build.gradle at the app level.
In the `android/app/build.gradle` you need to change minifyEnabled to false in the `buildTypes` section.
For example: 

`buildTypes { 
        release {  
            resValue "string", "app_name", "your_app_name"  
            minifyEnabled true =>  minifyEnabled false 
        }  
`

**Comment by R4md4c** [comment]
Hey @tasacsachin, 

I've tried to reproduce the problem in the accompanied [SampleApp](https://github.com/onfido/react-native-sdk/tree/master/SampleApp) but unfortunately I couldn't, even with `minifyEnabled = true`, so I assume that you've got a problem in the SDK token generation itself that you've gotten from the server, which I'd recommend to double check the [Getting Started](https://github.com/onfido/react-native-sdk#getting-started) guide to obtain an SDK token.

Here's the reproducer project attached that I've tried to reproduced based on the SampleApp that was aforementioned, it's configured with `minifyEnabled=true` during release mode, and contains the same snippet that you've provided.

What you should do is head to [backend-server-example.js](https://github.com/onfido/react-native-sdk/blob/master/SampleApp/backend-server-example.js#L11), and paste your problematic token there.

Then run:
* yarn install
* cd android/ && ./gradlew installRelease

[reproducer-sampleapp.zip](https://github.com/onfido/react-native-sdk/files/7952463/reproducer-sampleapp.zip)

**Comment by gurpreet-onfido** [comment]
Hey @tasacsachin  Do you have any update for us?

**Comment by R4md4c** [comment]
Closing for inactivity, please feel free to reopen in case you have a reproducer, as we haven't managed to reproduce the issue.
