### ISSUE TITLE
Android sdk crashing before asking for camera permission

### ISSUE THREAD

**Issue by warrioru** [onfido/react-native-sdk#8]
Onfido sdk version: 1.2.3
React native version: 0.63.1

After clicking on enable camera on android devices, the app crashes with this message:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.freyasavings/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2795)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6543)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value
        at com.onfido.api.client.codec.binary.Base64.validateCharacter(Base64.java:762)
        at com.onfido.api.client.codec.binary.Base64.decode(Base64.java:463)
        at com.onfido.api.client.codec.binary.BaseNCodec.decode(BaseNCodec.java:414)
        at com.onfido.api.client.codec.binary.BaseNCodec.decode(BaseNCodec.java:397)
        at com.onfido.api.client.codec.binary.Base64.decodeBase64(Base64.java:660)
        at com.onfido.api.client.codec.binary.Base64.decodeBase64String(Base64.java:664)
        at com.onfido.api.client.token.sdk.SDKTokenExtractor.getTokenPart(SDKTokenExtractor.java:34)
        at com.onfido.api.client.token.sdk.SDKTokenExtractor.decodePayload(SDKTokenExtractor.java:21)
        at com.onfido.api.client.token.sdk.SDKToken.buildUrl(SDKToken.java:27)
        at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:34)
        at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient(Unknown Source:19)
        at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPI(Unknown Source:10)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:10)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:4)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:0)
        at com.onfido.dagger.internal.a.get(Unknown Source:15)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:34)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:2)
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject(Unknown Source:2)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setupPresenter(Unknown Source:12)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(Unknown Source:112)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2748)
```

**Comment by warrioru** [comment]
The sdk token was not correctly passed to the constructor. After modifying the token, it worked.

**Comment by GunnarAK** [comment]
I'm currently having this same issue. I pasted the sandbox token directly into the constructor so you'd think it should work instantly...
```
Onfido.start({
      sdkToken: <MY_SANDBOX_TOKEN>,
      flowSteps: {
        welcome: true,
        captureFace: {
          type: OnfidoCaptureType.VIDEO
        },
        captureDocument: {
          docType: OnfidoDocumentType.DRIVING_LICENCE,
          countryCode: OnfidoCountryCode.GBR
        }
      }
    })
      .then(res =>
        showDialog({
          type: "confirm",
          title: "Onfido success!",
          message: JSON.stringify(res)
        })
      )
      .catch(err =>
        showDialog({
          type: "confirm",
          title: "Onfido error",
          message: `Code: ${err.code}\nMessage: ${err.message}`
        })
      );
```

Error:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3335)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3474)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2081)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7643)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value
        at com.onfido.api.client.codec.binary.Base64.validateCharacter(Base64.java:762)
        at com.onfido.api.client.codec.binary.Base64.decode(Base64.java:463)
        at com.onfido.api.client.codec.binary.BaseNCodec.decode(BaseNCodec.java:414)
        at com.onfido.api.client.codec.binary.BaseNCodec.decode(BaseNCodec.java:397)
        at com.onfido.api.client.codec.binary.Base64.decodeBase64(Base64.java:660)
        at com.onfido.api.client.codec.binary.Base64.decodeBase64String(Base64.java:664)
        at com.onfido.api.client.token.sdk.SDKTokenExtractor.getTokenPart(SDKTokenExtractor.java:34)
        at com.onfido.api.client.token.sdk.SDKTokenExtractor.decodePayload(SDKTokenExtractor.java:21)
        at com.onfido.api.client.token.sdk.SDKToken.buildUrl(SDKToken.java:34)
        at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:34)
        at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient(Unknown Source:18)
        at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPI(Unknown Source:9)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:10)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:4)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:0)
        at com.onfido.dagger.internal.a.get(Unknown Source:15)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:34)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:2)
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject(Unknown Source:2)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(Unknown Source:20)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
```

**Comment by warrioru** [comment]
You should not use your sandbox token. Instead use the generated sdk token which comes back after creating an applicant.

**Comment by GunnarAK** [comment]
Ah correct! I was able to create an applicant by using Onfido's Postman environment:
https://documentation.onfido.com/#postman
